/**
 * Блог: економіка постачання.
 *
 * Кластер запитів «ціна за кг / за літр / за м³ / за тонну» — найгарячіший
 * комерційний попит у ніші й одночасно найбільша плутанина: пропозиції
 * приходять у різних одиницях, і порівняти їх без перерахунку неможливо.
 */
import {
  SEED_UPDATED_AT,
  body,
  categoryPath,
  faq,
  img,
  productPath,
} from "./helpers.ts";
import {
  catSelection,
  seedAuthor,
  seedProduct,
  type SeedPost,
} from "./blog.ts";
import { tankCategories } from "./tanks.ts";

const catTanksCo2 = tankCategories.find((c) => c._id === "cat-tanks-co2")!;

const tank10 = seedProduct("product-tank-co2-10");
const tank30 = seedProduct("product-tank-co2-30");
const install = seedProduct("product-installation-turnkey");
const vaporizer300 = seedProduct("product-co2-vaporizer-300");

const PHOTO = {
  tankVertical: "/images/catalog/cryogenic-storage-tank-vertical.webp",
  microbulk: "/images/catalog/microbulk-tank-with-piping.webp",
  tankVaporizer: "/images/catalog/cryogenic-tank-with-ambient-vaporizer.webp",
  distribution: "/images/supplyPage/distribution/imageOne.webp",
};

/* ─── Стаття: одиниці виміру й порівняння пропозицій ───────────────────── */

export const postPriceUnits: SeedPost = {
  _id: "post-co2-price-units",
  _updatedAt: SEED_UPDATED_AT,
  title: {
    en: "CO₂ price per kilogram, litre, cubic metre or tonne: how to compare quotes",
    uk: "Ціна CO₂ за кілограм, літр, кубометр чи тонну: як порівнювати пропозиції",
    ru: "Цена CO₂ за килограмм, литр, кубометр или тонну: как сравнивать предложения",
  },
  slug: {
    en: { current: "co2-price-per-kg-m3-tonne" },
    uk: { current: "tsina-co2-za-kg-m3-tonnu" },
    ru: { current: "tsena-co2-za-kg-m3-tonnu" },
  },
  isPublished: true,
  isFeatured: true,
  publishedAt: "2026-09-07T11:00:00Z",
  updatedAt: "2026-09-07T11:00:00Z",
  readingTimeMinutes: 4,
  author: seedAuthor,
  categories: [catSelection],
  tags: ["CO2", "ціна", "розрахунок"],
  coverImage: img(PHOTO.tankVertical, {
    en: "Vertical cryogenic storage tank for liquid CO₂ on a production site",
    uk: "Вертикальна кріогенна ємність для рідкого CO₂ на виробничому майданчику",
    ru: "Вертикальная криогенная ёмкость для жидкого CO₂ на производственной площадке",
  }),
  excerpt: {
    en: "One supplier quotes per cylinder, another per kilogram, a third per cubic metre of gas. Conversion tables and the four traps that make the cheapest-looking offer the most expensive.",
    uk: "Один постачальник дає ціну за балон, другий за кілограм, третій за кубометр газу. Таблиці перерахунку і чотири пастки, через які найдешевша на вигляд пропозиція виявляється найдорожчою.",
    ru: "Один поставщик даёт цену за баллон, второй за килограмм, третий за кубометр газа. Таблицы пересчёта и четыре ловушки, из-за которых самое дешёвое на вид предложение оказывается самым дорогим.",
  },
  body: body(
    {
      en: [
        ["p", "Three quotes for the same CO₂ arrive in three different units: hryvnia per cylinder, per kilogram and per cubic metre of gas. They cannot be compared as they stand, and the differences between them are big enough to decide the contract."],
        ["h2", "One product, three units"],
        ["p", "CO₂ travels through three states in the same supply chain. It is stored as a liquid under pressure, sold by mass, and consumed as a gas. Each stage has its own natural unit, and all of them are correct — they just measure different things."],
        ["tbl", "Base conversions for carbon dioxide", "Unit | Equals | Note", "1 kg of liquid CO₂ | ≈ 0.54 m³ of gas | at 15 °C and 1 bar", "1 m³ of liquid in a tank | ≈ 1.03 t | density at −20 °C and about 20 bar", "1 tonne | ≈ 540 m³ of gas ≈ 0.97 m³ of liquid | ", "40 l cylinder | ≈ 24 kg ≈ 13 m³ of gas | filling ratio 0.6 kg/l", "30 m³ tank, 95% full | ≈ 29 t ≈ 15 700 m³ of gas | "],
        ["p", "**Always convert everything to price per kilogram.** Mass is the only unit that does not depend on temperature, pressure or how full the vessel is, so it is the only honest basis for comparison."],
        ["h2", "The same arithmetic for other gases"],
        ["p", "If you buy nitrogen, oxygen or argon as well, the conversion factors differ — and the difference is large. A cubic metre of liquid argon holds nearly twice the mass of a cubic metre of liquid nitrogen."],
        ["tbl", "Liquid density and gas yield at 15 °C, 1 bar", "Gas | Liquid density, kg/m³ | 1 kg gives | Boiling point at 1 bar", "CO₂ | ≈ 1030 (at −20 °C, 20 bar) | 0.54 m³ | −78.5 °C, sublimation", "Nitrogen N₂ | 809 | 0.84 m³ | −196 °C", "Oxygen O₂ | 1141 | 0.74 m³ | −183 °C", "Argon Ar | 1394 | 0.59 m³ | −186 °C"],
        ["img", PHOTO.distribution, "Road tanker delivering liquefied gas to a customer site", "Bulk delivery is where the price per kilogram drops the most — provided the minimum shipment fits your consumption"],
        ["h2", "What a quote hides"],
        ["tbl", "", "Supply model | Quoted in | Convert to | The trap", "Cylinder refill | UAH per cylinder | UAH per kg | 1–2 kg heel stays in the cylinder", "Cylinder exchange | UAH per cylinder | UAH per kg | the fleet is not yours; damage is charged to you", "Road tanker | UAH per kg or per t | UAH per kg | minimum shipment of 5–20 t", "Tank rental | UAH per month | add to UAH per kg | ties you to one supplier's gas price"],
        ["h2", "Four traps worth checking before you sign"],
        ["li", "**Minimum shipment.** A low price per tonne is meaningless if the minimum load is 20 tonnes and you use three a month."],
        ["li", "**Delivery included or not.** For bulk gas the logistics can be a noticeable share of the price, and it depends on the distance to the filling plant."],
        ["li", "**Boil-off during storage.** A vacuum-insulated tank loses roughly 0.15–0.3% a day. At slow turnover this quietly adds several percent to the real price."],
        ["li", "**Rental and deposits.** Cylinder deposits and tank rent are not part of the price per kilogram, but they are part of the bill."],
        ["h2", "A worked comparison"],
        ["p", "A food producer uses 2.5 tonnes of CO₂ a month. Quote A: cylinder exchange, 40 l for a fixed price per cylinder. At 24 kg usable per cylinder that is 105 cylinders a month, plus 1.5 kg of heel each — about 160 kg, or 6% of the volume, paid for and never used. Quote B: tanker delivery into a customer-owned tank, priced per kilogram, minimum shipment 5 tonnes — that is a delivery every two months."],
        ["p", `Once both are converted to hryvnia per kilogram, bulk supply is typically two to four times cheaper than cylinders. The catch is that Quote B only works if there is somewhere to put five tonnes: a [10 m³ tank](${productPath(tank10, "en")}) holds about 9.5 t, so it takes a full delivery with room to spare.`],
        ["h2", "The order in which to decide"],
        ["no", "Convert every quote to price per kilogram, including deposits, rent and the heel."],
        ["no", "Check the minimum shipment against your monthly consumption."],
        ["no", "Work out the storage volume that a minimum shipment requires."],
        ["no", `Only then choose the [tank](${categoryPath(catTanksCo2, "en")}) and the vaporizer — the equipment follows the supply arithmetic, not the other way round.`],
        ["cta", "Want the arithmetic done for you?", "Send us your quotes and monthly consumption. We will convert everything to price per kilogram and show which option wins on your numbers.", "Send the figures", "/contacts"],
      ],
      uk: [
        ["p", "Три пропозиції на той самий CO₂ приходять у трьох різних одиницях: гривень за балон, за кілограм і за кубометр газу. У такому вигляді їх не порівняти, а різниця між ними достатньо велика, щоб вирішити долю контракту."],
        ["h2", "Один продукт, три одиниці"],
        ["p", "CO₂ проходить три стани в межах одного ланцюга постачання. Зберігається як рідина під тиском, продається за масою, споживається як газ. У кожного етапу своя природна одиниця, і всі вони правильні — просто міряють різне."],
        ["tbl", "Базові перерахунки для вуглекислоти", "Одиниця | Дорівнює | Примітка", "1 кг рідкого CO₂ | ≈ 0,54 м³ газу | за 15 °C і 1 бар", "1 м³ рідини в ємності | ≈ 1,03 т | густина за −20 °C і близько 20 бар", "1 тонна | ≈ 540 м³ газу ≈ 0,97 м³ рідини | ", "Балон 40 л | ≈ 24 кг ≈ 13 м³ газу | норма наповнення 0,6 кг/л", "Ємність 30 м³, заповнення 95% | ≈ 29 т ≈ 15 700 м³ газу | "],
        ["p", "**Зводьте все до ціни за кілограм.** Маса — єдина одиниця, яка не залежить від температури, тиску й ступеня заповнення посудини, тож лише вона дає чесну основу для порівняння."],
        ["h2", "Та сама арифметика для інших газів"],
        ["p", "Якщо ви купуєте ще й азот, кисень або аргон, коефіцієнти перерахунку інші — і різниця велика. Кубометр рідкого аргону містить майже вдвічі більшу масу, ніж кубометр рідкого азоту."],
        ["tbl", "Густина рідини й вихід газу за 15 °C і 1 бар", "Газ | Густина рідини, кг/м³ | 1 кг дає | Т кипіння за 1 бар", "CO₂ | ≈ 1030 (за −20 °C, 20 бар) | 0,54 м³ | −78,5 °C, сублімація", "Азот N₂ | 809 | 0,84 м³ | −196 °C", "Кисень O₂ | 1141 | 0,74 м³ | −183 °C", "Аргон Ar | 1394 | 0,59 м³ | −186 °C"],
        ["img", PHOTO.distribution, "Автоцистерна доставляє зріджений газ на майданчик замовника", "Саме на доставці автоцистерною ціна за кілограм падає найбільше — якщо мінімальна партія відповідає вашому споживанню"],
        ["h2", "Що ховається в пропозиції"],
        ["tbl", "", "Модель постачання | У чому ціна | До чого звести | Пастка", "Заправка балонів | грн за балон | грн за кг | 1–2 кг залишку лишаються в балоні", "Обмін балонів | грн за балон | грн за кг | парк не ваш, за пошкодження платите ви", "Автоцистерна | грн за кг або за т | грн за кг | мінімальна партія 5–20 т", "Оренда ємності | грн на місяць | додати до грн за кг | привʼязує до ціни газу одного постачальника"],
        ["h2", "Чотири пастки, які варто перевірити до підпису"],
        ["li", "**Мінімальна партія.** Низька ціна за тонну нічого не варта, якщо мінімальне відвантаження — 20 тонн, а ви споживаєте три на місяць."],
        ["li", "**Доставка включена чи ні.** Для газу навалом логістика може бути помітною часткою ціни й залежить від відстані до наповнювальної станції."],
        ["li", "**Втрати на зберіганні.** Вакуумно-ізольована ємність втрачає приблизно 0,15–0,3% на добу. За повільної оборотності це тихо додає кілька відсотків до реальної ціни."],
        ["li", "**Оренда й застави.** Застава за балони й оренда ємності не входять у ціну за кілограм, але входять у рахунок."],
        ["h2", "Приклад порівняння"],
        ["p", "Харчове виробництво споживає 2,5 тонни CO₂ на місяць. Пропозиція А: обмін балонів 40 л за фіксованою ціною за балон. За 24 кг корисних із балона це 105 балонів на місяць плюс по 1,5 кг залишку в кожному — близько 160 кг, тобто 6% обсягу, оплачених і невикористаних. Пропозиція Б: доставка автоцистерною у власну ємність, ціна за кілограм, мінімальна партія 5 тонн — тобто поставка раз на два місяці."],
        ["p", `Коли обидві зведені до гривень за кілограм, газ навалом зазвичай виходить у два-чотири рази дешевшим за балони. Заковика в тому, що пропозиція Б працює лише якщо є куди подіти пʼять тонн: [ємність на 10 м³](${productPath(tank10, "uk")}) вміщає близько 9,5 т, тож приймає повну поставку із запасом.`],
        ["h2", "У якому порядку ухвалювати рішення"],
        ["no", "Зведіть кожну пропозицію до ціни за кілограм разом із заставами, орендою та залишком."],
        ["no", "Звірте мінімальну партію зі своїм місячним споживанням."],
        ["no", "Порахуйте обʼєм зберігання, якого вимагає мінімальна партія."],
        ["no", `І лише тоді обирайте [ємність](${categoryPath(catTanksCo2, "uk")}) та випарник — обладнання йде за арифметикою постачання, а не навпаки.`],
        ["cta", "Хочете, щоб арифметику зробили за вас?", "Надішліть свої пропозиції й місячне споживання. Зведемо все до ціни за кілограм і покажемо, який варіант виграє саме на ваших цифрах.", "Надіслати цифри", "/uk/contacts"],
      ],
      ru: [
        ["p", "Три предложения на один и тот же CO₂ приходят в трёх разных единицах: гривен за баллон, за килограмм и за кубометр газа. В таком виде их не сравнить, а разница между ними достаточно велика, чтобы решить судьбу контракта."],
        ["h2", "Один продукт, три единицы"],
        ["p", "CO₂ проходит три состояния в пределах одной цепочки поставки. Хранится как жидкость под давлением, продаётся по массе, потребляется как газ. У каждого этапа своя естественная единица, и все они правильные — просто меряют разное."],
        ["tbl", "Базовые пересчёты для углекислоты", "Единица | Равна | Примечание", "1 кг жидкого CO₂ | ≈ 0,54 м³ газа | при 15 °C и 1 бар", "1 м³ жидкости в ёмкости | ≈ 1,03 т | плотность при −20 °C и около 20 бар", "1 тонна | ≈ 540 м³ газа ≈ 0,97 м³ жидкости | ", "Баллон 40 л | ≈ 24 кг ≈ 13 м³ газа | норма наполнения 0,6 кг/л", "Ёмкость 30 м³, заполнение 95% | ≈ 29 т ≈ 15 700 м³ газа | "],
        ["p", "**Сводите всё к цене за килограмм.** Масса — единственная единица, которая не зависит от температуры, давления и степени заполнения сосуда, поэтому только она даёт честную основу для сравнения."],
        ["h2", "Та же арифметика для других газов"],
        ["p", "Если вы покупаете ещё и азот, кислород или аргон, коэффициенты пересчёта другие — и разница велика. Кубометр жидкого аргона содержит почти вдвое большую массу, чем кубометр жидкого азота."],
        ["tbl", "Плотность жидкости и выход газа при 15 °C и 1 бар", "Газ | Плотность жидкости, кг/м³ | 1 кг даёт | Т кипения при 1 бар", "CO₂ | ≈ 1030 (при −20 °C, 20 бар) | 0,54 м³ | −78,5 °C, сублимация", "Азот N₂ | 809 | 0,84 м³ | −196 °C", "Кислород O₂ | 1141 | 0,74 м³ | −183 °C", "Аргон Ar | 1394 | 0,59 м³ | −186 °C"],
        ["img", PHOTO.distribution, "Автоцистерна доставляет сжиженный газ на площадку заказчика", "Именно на доставке автоцистерной цена за килограмм падает сильнее всего — если минимальная партия соответствует вашему потреблению"],
        ["h2", "Что прячется в предложении"],
        ["tbl", "", "Модель поставки | В чём цена | К чему свести | Ловушка", "Заправка баллонов | грн за баллон | грн за кг | 1–2 кг остатка остаются в баллоне", "Обмен баллонов | грн за баллон | грн за кг | парк не ваш, за повреждения платите вы", "Автоцистерна | грн за кг или за т | грн за кг | минимальная партия 5–20 т", "Аренда ёмкости | грн в месяц | добавить к грн за кг | привязывает к цене газа одного поставщика"],
        ["h2", "Четыре ловушки, которые стоит проверить до подписи"],
        ["li", "**Минимальная партия.** Низкая цена за тонну ничего не стоит, если минимальная отгрузка — 20 тонн, а вы потребляете три в месяц."],
        ["li", "**Доставка включена или нет.** Для газа навалом логистика может быть заметной долей цены и зависит от расстояния до наполнительной станции."],
        ["li", "**Потери при хранении.** Вакуумно-изолированная ёмкость теряет примерно 0,15–0,3% в сутки. При медленной оборачиваемости это тихо добавляет несколько процентов к реальной цене."],
        ["li", "**Аренда и залоги.** Залог за баллоны и аренда ёмкости не входят в цену за килограмм, но входят в счёт."],
        ["h2", "Пример сравнения"],
        ["p", "Пищевое производство потребляет 2,5 тонны CO₂ в месяц. Предложение А: обмен баллонов 40 л по фиксированной цене за баллон. При 24 кг полезных из баллона это 105 баллонов в месяц плюс по 1,5 кг остатка в каждом — около 160 кг, то есть 6% объёма, оплаченных и неиспользованных. Предложение Б: доставка автоцистерной в собственную ёмкость, цена за килограмм, минимальная партия 5 тонн — то есть поставка раз в два месяца."],
        ["p", `Когда обе сведены к гривнам за килограмм, газ навалом обычно выходит в два-четыре раза дешевле баллонов. Загвоздка в том, что предложение Б работает только если есть куда деть пять тонн: [ёмкость на 10 м³](${productPath(tank10, "ru")}) вмещает около 9,5 т, поэтому принимает полную поставку с запасом.`],
        ["h2", "В каком порядке принимать решение"],
        ["no", "Сведите каждое предложение к цене за килограмм вместе с залогами, арендой и остатком."],
        ["no", "Сверьте минимальную партию со своим месячным потреблением."],
        ["no", "Посчитайте объём хранения, которого требует минимальная партия."],
        ["no", `И только тогда выбирайте [ёмкость](${categoryPath(catTanksCo2, "ru")}) и испаритель — оборудование идёт за арифметикой поставки, а не наоборот.`],
        ["cta", "Хотите, чтобы арифметику сделали за вас?", "Пришлите свои предложения и месячное потребление. Сведём всё к цене за килограмм и покажем, какой вариант выигрывает именно на ваших цифрах.", "Отправить цифры", "/ru/contacts"],
      ],
    },
    "pu",
  ),
  faq: [
    faq(
      "faq-price-1",
      {
        en: "How many cubic metres of gas are in one kilogram of CO₂?",
        uk: "Скільки кубометрів газу в одному кілограмі CO₂?",
        ru: "Сколько кубометров газа в одном килограмме CO₂?",
      },
      {
        en: "About 0.54 m³ at 15 °C and atmospheric pressure. The figure moves with temperature — roughly 0.51 m³ at 0 °C and 0.55 m³ at 20 °C — so a quote in cubic metres should always state the reference conditions, otherwise there is nothing to compare.",
        uk: "Близько 0,54 м³ за 15 °C і атмосферного тиску. Значення змінюється з температурою — приблизно 0,51 м³ за 0 °C і 0,55 м³ за 20 °C — тож у пропозиції в кубометрах мають бути вказані умови приведення, інакше порівнювати нема з чим.",
        ru: "Около 0,54 м³ при 15 °C и атмосферном давлении. Значение меняется с температурой — примерно 0,51 м³ при 0 °C и 0,55 м³ при 20 °C — поэтому в предложении в кубометрах должны быть указаны условия приведения, иначе сравнивать не с чем.",
      },
    ),
    faq(
      "faq-price-2",
      {
        en: "Why is bulk CO₂ so much cheaper than cylinders?",
        uk: "Чому CO₂ навалом настільки дешевший за балони?",
        ru: "Почему CO₂ навалом настолько дешевле баллонов?",
      },
      {
        en: "Because the cylinder price carries a whole layer of work that bulk delivery skips: filling each cylinder individually, inspecting and testing the fleet, transporting steel that weighs three times more than the gas inside it, and handling returns. A tanker moves 20 tonnes in one operation.",
        uk: "Бо в ціні балона сидить цілий шар роботи, якого немає в доставці навалом: наповнення кожного балона окремо, огляд і випробування парку, перевезення сталі, яка важить утричі більше за газ усередині, і обробка повернень. Автоцистерна перевозить 20 тонн за одну операцію.",
        ru: "Потому что в цене баллона сидит целый слой работы, которого нет в доставке навалом: наполнение каждого баллона отдельно, осмотр и испытание парка, перевозка стали, которая весит втрое больше газа внутри, и обработка возвратов. Автоцистерна перевозит 20 тонн за одну операцию.",
      },
    ),
  ],
  relatedProducts: [tank10, tank30, vaporizer300],
  relatedPosts: [],
  seo: {
    metaTitle: {
      en: "CO₂ price per kg, m³ and tonne: conversion tables and how to compare",
      uk: "Ціна CO₂ за кг, м³ і тонну: таблиці перерахунку й як порівнювати",
      ru: "Цена CO₂ за кг, м³ и тонну: таблицы пересчёта и как сравнивать",
    },
    metaDescription: {
      en: "1 kg of CO₂ = 0.54 m³ of gas, 1 m³ of liquid ≈ 1.03 t. Conversion tables for CO₂, N₂, O₂ and Ar plus the traps hidden in cylinder, tanker and rental quotes.",
      uk: "1 кг CO₂ = 0,54 м³ газу, 1 м³ рідини ≈ 1,03 т. Таблиці перерахунку для CO₂, N₂, O₂ та Ar і пастки, приховані в цінах на балони, цистерну й оренду.",
      ru: "1 кг CO₂ = 0,54 м³ газа, 1 м³ жидкости ≈ 1,03 т. Таблицы пересчёта для CO₂, N₂, O₂ и Ar и ловушки, спрятанные в ценах на баллоны, цистерну и аренду.",
    },
    keywords: {
      en: "CO2 price per kg, CO2 price per m3, liquid CO2 density",
      uk: "ціна CO2 за кг, вуглекислий газ ціна за м3, густина рідкого CO2",
      ru: "цена CO2 за кг, углекислый газ цена за м3, плотность жидкого CO2",
    },
  },
};

/* ─── Стаття: оренда чи купівля ємності ────────────────────────────────── */

export const postRentOrBuy: SeedPost = {
  _id: "post-tank-rent-or-buy",
  _updatedAt: SEED_UPDATED_AT,
  title: {
    en: "Rent or buy a cryogenic tank: what the two models really cost",
    uk: "Оренда чи купівля кріогенної ємності: у що насправді обходиться кожна модель",
    ru: "Аренда или покупка криогенной ёмкости: во что на самом деле обходится каждая модель",
  },
  slug: {
    en: { current: "rent-or-buy-cryogenic-tank" },
    uk: { current: "orenda-chy-kupivlya-kriogennoyi-yemnosti" },
    ru: { current: "arenda-ili-pokupka-kriogennoy-emkosti" },
  },
  isPublished: true,
  isFeatured: false,
  publishedAt: "2026-09-07T11:30:00Z",
  updatedAt: "2026-09-07T11:30:00Z",
  readingTimeMinutes: 4,
  author: seedAuthor,
  categories: [catSelection],
  tags: ["кріогенні ємності", "економіка", "постачання"],
  coverImage: img(PHOTO.microbulk, {
    en: "Microbulk cryogenic tank with piping installed at a customer facility",
    uk: "Мікробалк-ємність з обвʼязкою на майданчику замовника",
    ru: "Микробалк-ёмкость с обвязкой на площадке заказчика",
  }),
  excerpt: {
    en: "A rented tank looks free until you read the gas price attached to it. A comparison of the three ownership models, the numbers that decide between them, and what «turnkey» has to include.",
    uk: "Орендована ємність виглядає безкоштовною, поки не прочитати прикріплену до неї ціну газу. Порівняння трьох моделей володіння, цифри, які між ними вирішують, і що має входити в «під ключ».",
    ru: "Арендованная ёмкость выглядит бесплатной, пока не прочитать прикреплённую к ней цену газа. Сравнение трёх моделей владения, цифры, которые между ними решают, и что должно входить в «под ключ».",
  },
  body: body(
    {
      en: [
        ["p", "When consumption outgrows cylinders, the next question is not «which tank» but «whose tank». Three models are common in Ukraine, and the one that looks cheapest at the start is rarely the one that is cheapest over five years."],
        ["h2", "Three models"],
        ["tbl", "", "Model | Up-front cost | Gas price | Supplier choice | Suits", "Supplier's tank on loan | none or minimal | highest, fixed by contract | locked to one supplier | pilot projects, seasonal demand", "Long-term rental | installation only | above market, plus monthly rent | usually locked | 1–3 years horizon, uncertain volumes", "Own tank | full purchase and installation | market, open tender each time | free | stable consumption, long horizon"],
        ["p", "The mechanism behind the loan model is simple: the tank is paid for through the gas price. That is not a trick — it is financing, and for a plant testing a new process it is often the right call. It becomes expensive when the process turns out to be permanent and nobody revisits the contract."],
        ["h2", "The number that decides"],
        ["p", "Compare the premium per kilogram against the cost of ownership. If a supplier's tank comes with gas priced, say, 15% above the open market, and you use 3 tonnes a month, the premium is the equivalent of 450 kg of CO₂ every month. Multiply that by the price per kilogram and you get the annual cost of «free» equipment — then compare it with the purchase price of a tank."],
        ["p", `In practice the crossover sits around two to four years of stable consumption. Below that, renting is usually cheaper and definitely more flexible. Above it, a [30 m³ tank](${productPath(tank30, "en")}) of your own starts winning — and you regain the right to run a tender on gas.`],
        ["img", PHOTO.tankVaporizer, "Cryogenic tank with an ambient air vaporizer and piping on a prepared foundation", "An owned tank means the foundation, piping and vaporizer are yours too — and so is responsibility for them"],
        ["h2", "What ownership actually obliges you to"],
        ["li", "Registration and periodic technical examination of the pressure vessel."],
        ["li", "Maintaining the safety fittings: relief valves, gauges, level indication."],
        ["li", "Keeping the vacuum insulation intact — a vessel that loses vacuum starts venting product and has to be reworked."],
        ["li", "Trained personnel and a written procedure for receiving deliveries from a tanker."],
        ["p", "None of this is heavy, but it is not nothing. A service contract usually covers it for a fixed annual fee, and that fee belongs in the comparison alongside the rent it replaces."],
        ["h2", "What «turnkey» has to include"],
        ["p", `Whichever model you choose, the scope of works on site is the same. When you compare proposals, check that all of it is priced — a [turnkey installation](${productPath(install, "en")}) that quietly excludes the foundation or the commissioning is not comparable with one that includes them.`],
        ["li", "Foundation and site preparation, including tanker access."],
        ["li", "Delivery, lifting and setting of the vessel."],
        ["li", `The [vaporizer](${productPath(vaporizer300, "en")}) sized for peak demand, not average.`],
        ["li", "Piping to the point of use, with pressure regulation and safety fittings."],
        ["li", "Purging, leak testing, commissioning and personnel training."],
        ["li", "Documentation: passport, certificates, registration file."],
        ["h2", "Three questions before signing anything"],
        ["no", "What exactly is the gas price if the tank is supplied free — and how is it indexed?"],
        ["no", "Who owns the foundation and the piping when the contract ends?"],
        ["no", "How long is the exit notice, and is there a penalty for early termination?"],
        ["cta", "Comparing rental against purchase?", "Send your consumption and the terms on the table. We will show the five-year cost of both models on your numbers, with no obligation.", "Get the comparison", "/contacts"],
      ],
      uk: [
        ["p", "Коли споживання переростає балони, наступне питання — не «яка ємність», а «чия ємність». В Україні поширені три моделі, і та, що на старті виглядає найдешевшою, рідко лишається найдешевшою на горизонті пʼяти років."],
        ["h2", "Три моделі"],
        ["tbl", "", "Модель | Стартові витрати | Ціна газу | Вибір постачальника | Кому підходить", "Ємність постачальника у користування | немає або мінімальні | найвища, зафіксована договором | привʼязка до одного постачальника | пілотні проєкти, сезонний попит", "Довгострокова оренда | лише монтаж | вища за ринок плюс щомісячна оренда | зазвичай привʼязка | горизонт 1–3 роки, невизначені обсяги", "Власна ємність | повна купівля й монтаж | ринкова, тендер щоразу | вільний | стабільне споживання, довгий горизонт"],
        ["p", "Механіка моделі «ємність у користування» проста: обладнання оплачується через ціну газу. Це не хитрість, а фінансування, і для виробництва, яке тестує новий процес, часто правильний вибір. Дорогою вона стає тоді, коли процес виявився постійним, а до договору більше ніхто не повертався."],
        ["h2", "Цифра, яка вирішує"],
        ["p", "Порівнюйте надбавку за кілограм із вартістю володіння. Якщо ємність постачальника йде з газом, скажімо, на 15% дорожчим за відкритий ринок, а ви споживаєте 3 тонни на місяць, то надбавка щомісяця дорівнює 450 кг CO₂. Помножте це на ціну за кілограм — і отримаєте річну вартість «безкоштовного» обладнання. Далі порівняйте її з ціною купівлі ємності."],
        ["p", `На практиці точка перетину лежить десь у межах двох-чотирьох років стабільного споживання. Нижче — оренда зазвичай дешевша й точно гнучкіша. Вище — власна [ємність на 30 м³](${productPath(tank30, "uk")}) починає вигравати, і ви повертаєте собі право проводити тендер на газ.`],
        ["img", PHOTO.tankVaporizer, "Кріогенна ємність з атмосферним випарником і обвʼязкою на підготовленому фундаменті", "Власна ємність означає, що фундамент, обвʼязка й випарник теж ваші — разом із відповідальністю за них"],
        ["h2", "До чого насправді зобовʼязує володіння"],
        ["li", "Реєстрація та періодичний технічний огляд посудини під тиском."],
        ["li", "Підтримання запобіжної арматури: клапани, манометри, покажчики рівня."],
        ["li", "Збереження вакуумної ізоляції — посудина, що втратила вакуум, починає стравлювати продукт і потребує відновлення."],
        ["li", "Навчений персонал і письмовий порядок приймання поставки з автоцистерни."],
        ["p", "Нічого з цього не є важким, але й безкоштовним теж не є. Сервісний договір зазвичай закриває весь перелік за фіксовану річну суму, і ця сума має стояти в порівнянні поруч з орендою, яку вона заміщує."],
        ["h2", "Що має входити в «під ключ»"],
        ["p", `Яку б модель ви не обрали, обсяг робіт на майданчику однаковий. Порівнюючи пропозиції, перевірте, що враховано все: [монтаж під ключ](${productPath(install, "uk")}), із якого тихо випав фундамент або пусконалагодження, не можна порівнювати з тим, де вони є.`],
        ["li", "Фундамент і підготовка майданчика разом із підʼїздом для автоцистерни."],
        ["li", "Доставка, підйом і встановлення посудини."],
        ["li", `[Випарник](${productPath(vaporizer300, "uk")}), підібраний під пікове, а не середнє споживання.`],
        ["li", "Обвʼязка до точки споживання з редукуванням і запобіжною арматурою."],
        ["li", "Продування, випробування на герметичність, пусконалагодження й навчання персоналу."],
        ["li", "Документація: паспорт, сертифікати, реєстраційна справа."],
        ["h2", "Три питання перед будь-яким підписом"],
        ["no", "Яка саме ціна газу, якщо ємність надають безкоштовно, і як вона індексується?"],
        ["no", "Кому належать фундамент і обвʼязка після завершення договору?"],
        ["no", "Який строк попередження про вихід і чи є штраф за дострокове розірвання?"],
        ["cta", "Порівнюєте оренду з купівлею?", "Надішліть споживання й умови, які вам пропонують. Покажемо вартість обох моделей на пʼять років на ваших цифрах, без зобовʼязань.", "Отримати порівняння", "/uk/contacts"],
      ],
      ru: [
        ["p", "Когда потребление перерастает баллоны, следующий вопрос — не «какая ёмкость», а «чья ёмкость». В Украине распространены три модели, и та, что на старте выглядит самой дешёвой, редко остаётся самой дешёвой на горизонте пяти лет."],
        ["h2", "Три модели"],
        ["tbl", "", "Модель | Стартовые затраты | Цена газа | Выбор поставщика | Кому подходит", "Ёмкость поставщика в пользование | нет или минимальные | самая высокая, зафиксирована договором | привязка к одному поставщику | пилотные проекты, сезонный спрос", "Долгосрочная аренда | только монтаж | выше рынка плюс ежемесячная аренда | обычно привязка | горизонт 1–3 года, неопределённые объёмы", "Собственная ёмкость | полная покупка и монтаж | рыночная, тендер каждый раз | свободный | стабильное потребление, длинный горизонт"],
        ["p", "Механика модели «ёмкость в пользование» проста: оборудование оплачивается через цену газа. Это не хитрость, а финансирование, и для производства, которое тестирует новый процесс, часто правильный выбор. Дорогой она становится тогда, когда процесс оказался постоянным, а к договору больше никто не возвращался."],
        ["h2", "Цифра, которая решает"],
        ["p", "Сравнивайте надбавку за килограмм со стоимостью владения. Если ёмкость поставщика идёт с газом, скажем, на 15% дороже открытого рынка, а вы потребляете 3 тонны в месяц, то надбавка ежемесячно равна 450 кг CO₂. Умножьте это на цену за килограмм — и получите годовую стоимость «бесплатного» оборудования. Дальше сравните её с ценой покупки ёмкости."],
        ["p", `На практике точка пересечения лежит где-то в пределах двух-четырёх лет стабильного потребления. Ниже — аренда обычно дешевле и точно гибче. Выше — собственная [ёмкость на 30 м³](${productPath(tank30, "ru")}) начинает выигрывать, и вы возвращаете себе право проводить тендер на газ.`],
        ["img", PHOTO.tankVaporizer, "Криогенная ёмкость с атмосферным испарителем и обвязкой на подготовленном фундаменте", "Собственная ёмкость означает, что фундамент, обвязка и испаритель тоже ваши — вместе с ответственностью за них"],
        ["h2", "К чему на самом деле обязывает владение"],
        ["li", "Регистрация и периодическое техническое освидетельствование сосуда под давлением."],
        ["li", "Поддержание предохранительной арматуры: клапаны, манометры, указатели уровня."],
        ["li", "Сохранение вакуумной изоляции — сосуд, потерявший вакуум, начинает стравливать продукт и требует восстановления."],
        ["li", "Обученный персонал и письменный порядок приёмки поставки из автоцистерны."],
        ["p", "Ничто из этого не является тяжёлым, но и бесплатным тоже не является. Сервисный договор обычно закрывает весь перечень за фиксированную годовую сумму, и эта сумма должна стоять в сравнении рядом с арендой, которую она замещает."],
        ["h2", "Что должно входить в «под ключ»"],
        ["p", `Какую бы модель вы ни выбрали, объём работ на площадке одинаков. Сравнивая предложения, проверьте, что учтено всё: [монтаж под ключ](${productPath(install, "ru")}), из которого тихо выпал фундамент или пусконаладка, нельзя сравнивать с тем, где они есть.`],
        ["li", "Фундамент и подготовка площадки вместе с подъездом для автоцистерны."],
        ["li", "Доставка, подъём и установка сосуда."],
        ["li", `[Испаритель](${productPath(vaporizer300, "ru")}), подобранный под пиковое, а не среднее потребление.`],
        ["li", "Обвязка до точки потребления с редуцированием и предохранительной арматурой."],
        ["li", "Продувка, испытание на герметичность, пусконаладка и обучение персонала."],
        ["li", "Документация: паспорт, сертификаты, регистрационное дело."],
        ["h2", "Три вопроса перед любой подписью"],
        ["no", "Какая именно цена газа, если ёмкость предоставляют бесплатно, и как она индексируется?"],
        ["no", "Кому принадлежат фундамент и обвязка после завершения договора?"],
        ["no", "Какой срок предупреждения о выходе и есть ли штраф за досрочное расторжение?"],
        ["cta", "Сравниваете аренду с покупкой?", "Пришлите потребление и условия, которые вам предлагают. Покажем стоимость обеих моделей на пять лет на ваших цифрах, без обязательств.", "Получить сравнение", "/ru/contacts"],
      ],
    },
    "rb",
  ),
  faq: [
    faq(
      "faq-rent-1",
      {
        en: "Is a supplier's tank really free?",
        uk: "Чи справді ємність постачальника безкоштовна?",
        ru: "Действительно ли ёмкость поставщика бесплатна?",
      },
      {
        en: "The equipment is free; the gas is not. The cost of the tank is built into the price per kilogram over the term of the contract. That is a legitimate financing model — the mistake is to treat it as free and never compare the resulting gas price with the open market.",
        uk: "Безкоштовне обладнання, а не газ. Вартість ємності закладена в ціну за кілограм на строк договору. Це нормальна модель фінансування — помилка в тому, щоб вважати її безкоштовною й жодного разу не звірити отриману ціну газу з відкритим ринком.",
        ru: "Бесплатно оборудование, а не газ. Стоимость ёмкости заложена в цену за килограмм на срок договора. Это нормальная модель финансирования — ошибка в том, чтобы считать её бесплатной и ни разу не сверить полученную цену газа с открытым рынком.",
      },
    ),
    faq(
      "faq-rent-2",
      {
        en: "Can we buy a tank and keep our current gas supplier?",
        uk: "Чи можна купити ємність і лишити чинного постачальника газу?",
        ru: "Можно ли купить ёмкость и оставить текущего поставщика газа?",
      },
      {
        en: "Yes, and it usually improves the terms: once the equipment is no longer part of the deal, the supplier competes on gas price alone. Check that the fill connection and the delivery procedure match what their tankers use — this is a detail worth agreeing before the tank is ordered, not after.",
        uk: "Так, і зазвичай це покращує умови: коли обладнання більше не частина угоди, постачальник конкурує самою лише ціною газу. Перевірте, що заправне зʼєднання й порядок приймання збігаються з тим, що використовують його автоцистерни — це деталь, яку варто узгодити до замовлення ємності, а не після.",
        ru: "Да, и обычно это улучшает условия: когда оборудование больше не часть сделки, поставщик конкурирует одной лишь ценой газа. Проверьте, что заправочное соединение и порядок приёмки совпадают с тем, что используют его автоцистерны — эту деталь стоит согласовать до заказа ёмкости, а не после.",
      },
    ),
  ],
  relatedProducts: [tank30, install, vaporizer300],
  relatedPosts: [],
  seo: {
    metaTitle: {
      en: "Rent or buy a cryogenic tank: cost comparison over five years",
      uk: "Оренда чи купівля кріогенної ємності: порівняння вартості на пʼять років",
      ru: "Аренда или покупка криогенной ёмкости: сравнение стоимости на пять лет",
    },
    metaDescription: {
      en: "Supplier's tank, long-term rental or your own vessel: what each model costs, where the crossover point sits, and what a turnkey installation must include.",
      uk: "Ємність постачальника, довгострокова оренда чи власна посудина: у що обходиться кожна модель, де точка перетину і що має входити в монтаж під ключ.",
      ru: "Ёмкость поставщика, долгосрочная аренда или собственный сосуд: во что обходится каждая модель, где точка пересечения и что должно входить в монтаж под ключ.",
    },
    keywords: {
      en: "cryogenic tank rental, buy CO2 tank, tank ownership cost",
      uk: "оренда кріогенної ємності, купити ємність для CO2, вартість володіння",
      ru: "аренда криогенной емкости, купить емкость для CO2, стоимость владения",
    },
  },
};

export const economicsPosts: SeedPost[] = [postPriceUnits, postRentOrBuy];
